run-mysql8.0:
	docker-compose -f docker-compose-mysql8.0.yml up -d

stop-mysql8.0:
	docker-compose -f docker-compose-mysql8.0.yml stop
	docker-compose -f docker-compose-mysql8.0.yml rm

run-mysql5.7:
	docker-compose -f docker-compose-mysql5.7.yml up -d

stop-mysql5.7:
	docker-compose -f docker-compose-mysql5.7.yml stop
	docker-compose -f docker-compose-mysql5.7.yml rm
